version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=radioManagerDB'
      - 'POSTGRES_PASSWORD=W8r}a*B#~4'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    networks:
      - backend

volumes:
  postgres-data:
    driver: local

networks:
  backend:
    driver: bridge