spring.application.name=RadioManager

spring.docker.compose.enabled=true

logging.level.com.yourpackage=DEBUG

server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5433/radioManagerDB
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false

spring.flyway.locations=classpath:db/migration

jwt.secret=87d1122be0efcc86e8ffbd236811228370c6d5fcdfd95730f624014dd08ca4fa

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.messages.basename=messages
spring.messages.encoding=UTF-8

old.api.enabled=false

admin.initial.login=${ADMIN_INITIAL_LOGIN}
admin.initial.password=${ADMIN_INITIAL_PASSWORD}
admin.initial.name=${ADMIN_INITIAL_NAME}
admin.initial.surname=${ADMIN_INITIAL_SURNAME}
admin.initial.balance=${ADMIN_INITIAL_BALANCE}

system.entity.login=${SYSTEM_ENTITY_LOGIN}
system.entity.password=${SYSTEM_ENTITY_PASSWORD}
system.entity.name=${SYSTEM_ENTITY_NAME}
system.entity.surname=${SYSTEM_ENTITY_SURNAME}
system.entity.balance=${SYSTEM_ENTITY_BALANCE}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.debug=false

base.file-price=100.0
base.priority-multiplier=1.5

base.priority-high[0].start=07:00:00.0
base.priority-high[0].end=09:00:00.0

base.priority-high[1].start=12:00:00.0
base.priority-high[1].end=14:00:00.0

base.priority-high[2].start=17:00:00.0
base.priority-high[2].end=19:00:00.0

base.min-slot-duration=10